Feature/add ticket system
LuminateDev/LuminateDiscordBot pull request #5
Opened 2024-04-28 14:30 UTC by FabioGaming

Finalized the ticket system and added some additional documentation on the README file, ticket system should now be fully operational but future updates are required.

2024-04-30 07:26 UTC, FabioGaming reviewed
LGTM;

2024-04-30 07:53 UTC, lenajenichen requested changes
See GitHub Action comments. Change them first before approval.

2024-04-30 10:08 UTC, lenajenichen requested changes
Please change the stuff if needed, so we can get most of the warnings away.

2024-04-30 10:08 UTC, lenajenichen commented on LuminateDiscordBot/Commands.cs
> +                Text = $"Luminate - Your ideas shine bright"
String exists 2 times in the code already. Maybe a variable would be usefull for future usage.

2024-04-30 10:08 UTC, lenajenichen commented on LuminateDiscordBot/Commands.cs
> +                Text = $"Luminate - Your ideas shine bright"
Same here the string should be changed

2024-04-30 10:08 UTC, lenajenichen commented on LuminateDiscordBot/Commands.cs
> +                    Text = $"Luminate - Your ideas shine bright"
Same here the string should be changed

2024-04-30 10:08 UTC, lenajenichen commented on LuminateDiscordBot/Commands.cs
> +                    Text = "Luminate - Your ideas shine bright"
Same here the string should be changed

2024-04-30 10:08 UTC, lenajenichen commented on LuminateDiscordBot/Commands.cs
> +                Text = "Luminate - Your ideas shine bright"
Same here the string should be changed

2024-04-30 10:08 UTC, lenajenichen commented on LuminateDiscordBot/Commands.cs
> +                    Text = $"Luminate - Your ideas shine bright"
Same here the string should be changed

2024-04-30 10:08 UTC, lenajenichen commented on LuminateDiscordBot/Commands.cs
> +                Text = $"Luminate - Your ideas shine bright"
Same here the string should be changed

2024-04-30 10:08 UTC, lenajenichen commented on LuminateDiscordBot/Commands.cs
> +                    Text = $"Luminate - Your ideas shine bright"
Same here the string should be changed

2024-04-30 10:08 UTC, lenajenichen commented on LuminateDiscordBot/Commands.cs
> -                Text = $"Luminate - {Utils.DefaultSloganText}"
Why did we remove the Utils.DefaultSolganText?

2024-04-30 10:08 UTC, lenajenichen commented on LuminateDiscordBot/Commands.cs
> +            embed.Title = "Updated!";
We can also put this message in a variable since we're using it also more than once.

2024-04-30 10:08 UTC, lenajenichen commented on LuminateDiscordBot/Components.cs
> +                    Text = "Luminate - Your ideas shine bright"
Same as in Commands.cs. Not going to continue to mark all of them.

2024-04-30 10:08 UTC, lenajenichen commented on LuminateDiscordBot/DBManager.cs
> +            Objects.TicketCategory ticketCat = null;
Add a "?" so that the code knows it can be null.

2024-04-30 10:08 UTC, lenajenichen commented on LuminateDiscordBot/Models/TicketCreationModalModel.cs
> +        public string Reason { get; set; }
If Reason can be null, add "?" after "string".
`public string? Reason {get; set;}`

2024-04-30 10:08 UTC, lenajenichen commented on LuminateDiscordBot/Objects/TicketCategory.cs
> +        public string TicketTopic { get; set; }
Same as with the reason. Add "?" if it can be null.

2024-04-30 10:08 UTC, lenajenichen commented on LuminateDiscordBot/Objects/TicketCategory.cs
> +        public string CategoryAliasList { get; set; }
Same here.

2024-04-30 10:08 UTC, lenajenichen commented on LuminateDiscordBot/Objects/TicketCategory.cs
> +            return JsonSerializer.Deserialize<List<string>>(Convert.FromBase64String(this.CategoryAliasList));
Check if the List is null before returning it. 

`if (string.IsNullOrEmpty(CategoryAliasList))
    {
        // Handle whatever you might need when getting a null list.
        return new List<string>();
    }
    else
    {
        return JsonSerializer.Deserialize<List<string>>(Convert.FromBase64String(CategoryAliasList));
    }`

2024-04-30 10:17 UTC, FabioGaming commented on LuminateDiscordBot/Objects/TicketCategory.cs
> +            return JsonSerializer.Deserialize<List<string>>(Convert.FromBase64String(this.CategoryAliasList));
This function is deprecated since the origin ticket system will not be implemented and is a leftover for utility use

2024-04-30 10:46 UTC, lenajenichen commented on LuminateDiscordBot/Objects/TicketCategory.cs
> +            return JsonSerializer.Deserialize<List<string>>(Convert.FromBase64String(this.CategoryAliasList));
Problem is it **can** be null, therefore we have to either check if it's null or tell the code that it can't be null.

2024-04-30 11:03 UTC, TheVolpeDev commented on LuminateDiscordBot/Objects/TicketCategory.cs
> +            return JsonSerializer.Deserialize<List<string>>(Convert.FromBase64String(this.CategoryAliasList));
as stated in DBManager.InitDB, TicketKeywords is a TEXT type with a default value of "[]", in no case will the function not have a parseable string, it will however throw an exception because "[]" is not a valid Base64 string, this will later be refactored and replaced with proper JSON instead (since I have adapted to using Parameterized Queries its secure to do)

2024-05-22 12:20 UTC, lenajenichen approved these changes

2024-05-22 20:04 UTC, merged